<?php

namespace App\Console\Commands;

use App\Models\Permission;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class PermissionToJsClass extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'permission:js-class';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $permissions = Permission::query()
            ->select(['name', 'description'])
            ->orderBy('name')
            ->orderBy('created_at')
            ->get();

        $this->info('// '.Str::repeat('-', 60));
        $this->info('// Generated by CLI: php artisan permission:js-class');
        $this->info('// Date: '.date('Y-m-d H:i:s T'));
        $this->info('// Hash: '.hash('md5', $permissions->toJson()));
        $this->info('//');
        $this->info('// AUTO GENERATED SECTION');
        $this->info('// '.Str::repeat('-', 60));
        $this->line('');

        foreach ($permissions as $row) {
            $methodName = Str::of($row['description'])
                ->slug('_')
                ->camel();
            $constantName = Str::of($row['description'])
                ->slug('_')
                ->upper();
            $hasAny = $permissions->contains('name', $row['name'].'any');

            $canMethodName = 'can'.ucfirst($methodName);
            $this->info("{$canMethodName}(): boolean {");
            if ($hasAny) {
                $this->info("    if (this.can(Permission.{$constantName}_ANY)) {");
                $this->info('        return true;');
                $this->info('    }');
            }
            $this->info("    return this.can(Permission.{$constantName});");
            $this->info('}');
            $this->line('');

            $this->info("{$methodName}(): void | never {");
            $this->info("    if (!this.{$canMethodName}()) {");
            $this->info('        this.throw();');
            $this->info('    }');
            $this->info('}');
            $this->line('');

        }

        $this->info('// '.Str::repeat('-', 60));
        $this->info('// AUTO GENERATED SECTION END');
        $this->info('// '.Str::repeat('-', 60));

    }
}
