<?php

namespace App\Console\Commands;

use App\Models\Permission;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class PermissionToJsConstants extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'permission:js-constants';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate JavaScript constants for permissions';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $permissions = Permission::query()
            ->select(['name', 'description'])
            ->orderBy('name')
            ->orderBy('created_at')
            ->get();

        $this->info('// '.Str::repeat('-', 60));
        $this->info('// Generated by CLI: php artisan permission:js-constants');
        $this->info('// Date: '.date('Y-m-d H:i:s T'));
        $this->info('// Hash: '.hash('md5', $permissions->toJson()));
        $this->info('//');
        $this->info('// DO NOT EDIT THIS FILE MANUALLY');
        $this->info('// '.Str::repeat('-', 60));
        $this->line('');

        $constants = $permissions->map(function ($row) {
            $description = Str::of($row['description'])
                ->slug('_')
                ->upper();
            return "export const {$description} = '{$row['name']}';";
        });
        $this->info(implode("\n", $constants->toArray()));
    }
}
