// ------------------------------------------------------------
// Generated by CLI: php artisan permission:js-constants
// Date: 2025-11-01 07:00:18 UTC
// Hash: a5acb9361d4618fd4db2a76b6b40ab20
//
// DO NOT EDIT THIS FILE MANUALLY
// ------------------------------------------------------------

export const ACCESS_RESTRICTION_ADD_USER = 'accessrestriction:adduser';
export const ACCESS_RESTRICTION_ADD_USER_GROUP = 'accessrestriction:addusergroup';
export const ACCESS_RESTRICTION_CREATE = 'accessrestriction:create';
export const ACCESS_RESTRICTION_DELETE = 'accessrestriction:delete';
export const ACCESS_RESTRICTION_LIST_USER_GROUPS = 'accessrestriction:listusergroups';
export const ACCESS_RESTRICTION_LIST_USERS = 'accessrestriction:listusers';
export const ACCESS_RESTRICTION_REMOVE_USER = 'accessrestriction:removeuser';
export const ACCESS_RESTRICTION_REMOVE_USER_GROUP = 'accessrestriction:removeusergroup';
export const ACCESS_RESTRICTION_UPDATE = 'accessrestriction:update';
export const ACCESS_RESTRICTION_VIEW = 'accessrestriction:view';
export const ACTION_AUDIT_VIEW = 'actionaudit:view';
export const ASSET_ADD_ACCESS_GRANT = 'asset:addaccessgrant';
export const ASSET_CREATE = 'asset:create';
export const ASSET_DELETE = 'asset:delete';
export const ASSET_REMOVE_ACCESS_GRANT = 'asset:removeaccessgrant';
export const ASSET_UPDATE = 'asset:update';
export const ASSET_UPDATE_ADMIN_ACCOUNT = 'asset:updateadminaccount';
export const ASSET_VIEW = 'asset:view';
export const ASSET_VIEW_REQUESTABLE = 'asset:viewrequestable';
export const ORG_ADD_USER = 'org:adduser';
export const ORG_CREATE = 'org:create';
export const ORG_DELETE = 'org:delete';
export const ORG_LIST_USER_GROUPS = 'org:listusergroups';
export const ORG_LIST_USERS = 'org:listusers';
export const ORG_REMOVE_USER = 'org:removeuser';
export const ORG_UPDATE = 'org:update';
export const ORG_VIEW = 'org:view';
export const PERMISSION_VIEW = 'permission:view';
export const REQUEST_APPROVE = 'request:approve';
export const REQUEST_APPROVE_ANY = 'request:approveany';
export const REQUEST_CANCEL = 'request:cancel';
export const REQUEST_CANCEL_ANY = 'request:cancelany';
export const REQUEST_CREATE = 'request:create';
export const REQUEST_REJECT = 'request:reject';
export const REQUEST_REJECT_ANY = 'request:rejectany';
export const REQUEST_VIEW = 'request:view';
export const ROLE_CREATE = 'role:create';
export const ROLE_DELETE = 'role:delete';
export const ROLE_LIST_PERMISSIONS = 'role:listpermissions';
export const ROLE_UPDATE = 'role:update';
export const ROLE_UPDATE_PERMISSIONS = 'role:updatepermissions';
export const ROLE_VIEW = 'role:view';
export const SESSION_CANCEL = 'session:cancel';
export const SESSION_END = 'session:end';
export const SESSION_PERMISSION = 'session:permission';
export const SESSION_RETRIEVE_SECRET = 'session:retrievesecret';
export const SESSION_START = 'session:start';
export const SESSION_TERMINATE = 'session:terminate';
export const SESSION_TERMINATE_ANY = 'session:terminateany';
export const SESSION_VIEW = 'session:view';
export const USER_CHANGE_PASSWORD = 'user:changepassword';
export const USER_CREATE = 'user:create';
export const USER_DELETE_ANY = 'user:deleteany';
export const USER_ENROLL_TWO_FACTOR_AUTHENTICATION = 'user:enrolltwofactorauthentication';
export const USER_ENROLL_TWO_FACTOR_AUTHENTICATION_ANY = 'user:enrolltwofactorauthenticationany';
export const USER_RESET_PASSWORD_ANY = 'user:resetpasswordany';
export const USER_UPDATE = 'user:update';
export const USER_UPDATE_ANY = 'user:updateany';
export const USER_VIEW = 'user:view';
export const USER_VIEW_ANY = 'user:viewany';
export const USER_GROUP_ADD_USER = 'usergroup:adduser';
export const USER_GROUP_CREATE = 'usergroup:create';
export const USER_GROUP_DELETE = 'usergroup:delete';
export const USER_GROUP_REMOVE_USER = 'usergroup:removeuser';
export const USER_GROUP_UPDATE = 'usergroup:update';
export const USER_GROUP_VIEW = 'usergroup:view';
