import type { Me } from '$lib/models/user.js';
import { error } from '@sveltejs/kit';
import * as Permission from './constants.js';

/**
 * RBAC (Role-Based Access Control) authorization service
 * Evaluates user permissions for frontend authorization checks
 */
export class Rbac {
	private readonly permissions: Set<string>;
	private readonly isAdmin: boolean;

	/**
	 * Creates a new RBAC instance
	 * @param user - User with roles and permissions
	 */
	constructor(user: Me) {
		// Check if user has Admin role (bypasses all permission checks)
		this.isAdmin = user.roles.some((role) => role.name === 'Admin');

		// Build Set of permission names for O(1) lookup
		this.permissions = new Set(user.permissions.map((permission) => permission.name));
	}

	/**
	 * Checks if user has a specific permission
	 * @param name - Permission name (e.g., 'request:view')
	 * @returns true if user is Admin or has the permission, false otherwise (deny by default)
	 */
	can(name: string): boolean {
		if (this.isAdmin) {
			return true;
		}
		return this.permissions.has(name);
	}

	/**
	 * Checks if user has any of the specified permissions
	 * @param names - Array of permission names
	 * @returns true if user is Admin or has at least one permission, false otherwise
	 */
	hasAny(names: string[]): boolean {
		if (this.isAdmin) {
			return true;
		}
		return names.some((name) => this.permissions.has(name));
	}

	/**
	 * Checks if user has all of the specified permissions
	 * @param names - Array of permission names
	 * @returns true if user is Admin or has all permissions, false otherwise
	 */
	hasAll(names: string[]): boolean {
		if (this.isAdmin) {
			return true;
		}
		return names.every((name) => this.permissions.has(name));
	}

	authorize(name: string): void {
		if (!this.can(name)) {
			this.throw();
		}
	}

	throw(): never {
		throw error(403, 'You are not authorized to view this resource.');
	}

	// ------------------------------------------------------------
	// Generated by CLI: php artisan permission:js-class
	// Date: 2025-11-01 14:41:47 UTC
	// Hash: a5acb9361d4618fd4db2a76b6b40ab20
	//
	// AUTO GENERATED SECTION
	// ------------------------------------------------------------

	canAccessRestrictionAddUser(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_ADD_USER);
	}

	accessRestrictionAddUser(): void | never {
		if (!this.canAccessRestrictionAddUser()) {
			this.throw();
		}
	}

	canAccessRestrictionAddUserGroup(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_ADD_USER_GROUP);
	}

	accessRestrictionAddUserGroup(): void | never {
		if (!this.canAccessRestrictionAddUserGroup()) {
			this.throw();
		}
	}

	canAccessRestrictionCreate(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_CREATE);
	}

	accessRestrictionCreate(): void | never {
		if (!this.canAccessRestrictionCreate()) {
			this.throw();
		}
	}

	canAccessRestrictionDelete(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_DELETE);
	}

	accessRestrictionDelete(): void | never {
		if (!this.canAccessRestrictionDelete()) {
			this.throw();
		}
	}

	canAccessRestrictionListUserGroups(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_LIST_USER_GROUPS);
	}

	accessRestrictionListUserGroups(): void | never {
		if (!this.canAccessRestrictionListUserGroups()) {
			this.throw();
		}
	}

	canAccessRestrictionListUsers(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_LIST_USERS);
	}

	accessRestrictionListUsers(): void | never {
		if (!this.canAccessRestrictionListUsers()) {
			this.throw();
		}
	}

	canAccessRestrictionRemoveUser(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_REMOVE_USER);
	}

	accessRestrictionRemoveUser(): void | never {
		if (!this.canAccessRestrictionRemoveUser()) {
			this.throw();
		}
	}

	canAccessRestrictionRemoveUserGroup(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_REMOVE_USER_GROUP);
	}

	accessRestrictionRemoveUserGroup(): void | never {
		if (!this.canAccessRestrictionRemoveUserGroup()) {
			this.throw();
		}
	}

	canAccessRestrictionUpdate(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_UPDATE);
	}

	accessRestrictionUpdate(): void | never {
		if (!this.canAccessRestrictionUpdate()) {
			this.throw();
		}
	}

	canAccessRestrictionView(): boolean {
		return this.can(Permission.ACCESS_RESTRICTION_VIEW);
	}

	accessRestrictionView(): void | never {
		if (!this.canAccessRestrictionView()) {
			this.throw();
		}
	}

	canActionAuditView(): boolean {
		return this.can(Permission.ACTION_AUDIT_VIEW);
	}

	actionAuditView(): void | never {
		if (!this.canActionAuditView()) {
			this.throw();
		}
	}

	canAssetAddAccessGrant(): boolean {
		return this.can(Permission.ASSET_ADD_ACCESS_GRANT);
	}

	assetAddAccessGrant(): void | never {
		if (!this.canAssetAddAccessGrant()) {
			this.throw();
		}
	}

	canAssetCreate(): boolean {
		return this.can(Permission.ASSET_CREATE);
	}

	assetCreate(): void | never {
		if (!this.canAssetCreate()) {
			this.throw();
		}
	}

	canAssetDelete(): boolean {
		return this.can(Permission.ASSET_DELETE);
	}

	assetDelete(): void | never {
		if (!this.canAssetDelete()) {
			this.throw();
		}
	}

	canAssetRemoveAccessGrant(): boolean {
		return this.can(Permission.ASSET_REMOVE_ACCESS_GRANT);
	}

	assetRemoveAccessGrant(): void | never {
		if (!this.canAssetRemoveAccessGrant()) {
			this.throw();
		}
	}

	canAssetUpdate(): boolean {
		return this.can(Permission.ASSET_UPDATE);
	}

	assetUpdate(): void | never {
		if (!this.canAssetUpdate()) {
			this.throw();
		}
	}

	canAssetUpdateAdminAccount(): boolean {
		return this.can(Permission.ASSET_UPDATE_ADMIN_ACCOUNT);
	}

	assetUpdateAdminAccount(): void | never {
		if (!this.canAssetUpdateAdminAccount()) {
			this.throw();
		}
	}

	canAssetView(): boolean {
		return this.can(Permission.ASSET_VIEW);
	}

	assetView(): void | never {
		if (!this.canAssetView()) {
			this.throw();
		}
	}

	canAssetViewRequestable(): boolean {
		return this.can(Permission.ASSET_VIEW_REQUESTABLE);
	}

	assetViewRequestable(): void | never {
		if (!this.canAssetViewRequestable()) {
			this.throw();
		}
	}

	canOrgAddUser(): boolean {
		return this.can(Permission.ORG_ADD_USER);
	}

	orgAddUser(): void | never {
		if (!this.canOrgAddUser()) {
			this.throw();
		}
	}

	canOrgCreate(): boolean {
		return this.can(Permission.ORG_CREATE);
	}

	orgCreate(): void | never {
		if (!this.canOrgCreate()) {
			this.throw();
		}
	}

	canOrgDelete(): boolean {
		return this.can(Permission.ORG_DELETE);
	}

	orgDelete(): void | never {
		if (!this.canOrgDelete()) {
			this.throw();
		}
	}

	canOrgListUserGroups(): boolean {
		return this.can(Permission.ORG_LIST_USER_GROUPS);
	}

	orgListUserGroups(): void | never {
		if (!this.canOrgListUserGroups()) {
			this.throw();
		}
	}

	canOrgListUsers(): boolean {
		return this.can(Permission.ORG_LIST_USERS);
	}

	orgListUsers(): void | never {
		if (!this.canOrgListUsers()) {
			this.throw();
		}
	}

	canOrgRemoveUser(): boolean {
		return this.can(Permission.ORG_REMOVE_USER);
	}

	orgRemoveUser(): void | never {
		if (!this.canOrgRemoveUser()) {
			this.throw();
		}
	}

	canOrgUpdate(): boolean {
		return this.can(Permission.ORG_UPDATE);
	}

	orgUpdate(): void | never {
		if (!this.canOrgUpdate()) {
			this.throw();
		}
	}

	canOrgView(): boolean {
		return this.can(Permission.ORG_VIEW);
	}

	orgView(): void | never {
		if (!this.canOrgView()) {
			this.throw();
		}
	}

	canPermissionView(): boolean {
		return this.can(Permission.PERMISSION_VIEW);
	}

	permissionView(): void | never {
		if (!this.canPermissionView()) {
			this.throw();
		}
	}

	canRequestApprove(): boolean {
		if (this.can(Permission.REQUEST_APPROVE_ANY)) {
			return true;
		}
		return this.can(Permission.REQUEST_APPROVE);
	}

	requestApprove(): void | never {
		if (!this.canRequestApprove()) {
			this.throw();
		}
	}

	canRequestApproveAny(): boolean {
		return this.can(Permission.REQUEST_APPROVE_ANY);
	}

	requestApproveAny(): void | never {
		if (!this.canRequestApproveAny()) {
			this.throw();
		}
	}

	canRequestCancel(): boolean {
		if (this.can(Permission.REQUEST_CANCEL_ANY)) {
			return true;
		}
		return this.can(Permission.REQUEST_CANCEL);
	}

	requestCancel(): void | never {
		if (!this.canRequestCancel()) {
			this.throw();
		}
	}

	canRequestCancelAny(): boolean {
		return this.can(Permission.REQUEST_CANCEL_ANY);
	}

	requestCancelAny(): void | never {
		if (!this.canRequestCancelAny()) {
			this.throw();
		}
	}

	canRequestCreate(): boolean {
		return this.can(Permission.REQUEST_CREATE);
	}

	requestCreate(): void | never {
		if (!this.canRequestCreate()) {
			this.throw();
		}
	}

	canRequestReject(): boolean {
		if (this.can(Permission.REQUEST_REJECT_ANY)) {
			return true;
		}
		return this.can(Permission.REQUEST_REJECT);
	}

	requestReject(): void | never {
		if (!this.canRequestReject()) {
			this.throw();
		}
	}

	canRequestRejectAny(): boolean {
		return this.can(Permission.REQUEST_REJECT_ANY);
	}

	requestRejectAny(): void | never {
		if (!this.canRequestRejectAny()) {
			this.throw();
		}
	}

	canRequestView(): boolean {
		return this.can(Permission.REQUEST_VIEW);
	}

	requestView(): void | never {
		if (!this.canRequestView()) {
			this.throw();
		}
	}

	canRoleCreate(): boolean {
		return this.can(Permission.ROLE_CREATE);
	}

	roleCreate(): void | never {
		if (!this.canRoleCreate()) {
			this.throw();
		}
	}

	canRoleDelete(): boolean {
		return this.can(Permission.ROLE_DELETE);
	}

	roleDelete(): void | never {
		if (!this.canRoleDelete()) {
			this.throw();
		}
	}

	canRoleListPermissions(): boolean {
		return this.can(Permission.ROLE_LIST_PERMISSIONS);
	}

	roleListPermissions(): void | never {
		if (!this.canRoleListPermissions()) {
			this.throw();
		}
	}

	canRoleUpdate(): boolean {
		return this.can(Permission.ROLE_UPDATE);
	}

	roleUpdate(): void | never {
		if (!this.canRoleUpdate()) {
			this.throw();
		}
	}

	canRoleUpdatePermissions(): boolean {
		return this.can(Permission.ROLE_UPDATE_PERMISSIONS);
	}

	roleUpdatePermissions(): void | never {
		if (!this.canRoleUpdatePermissions()) {
			this.throw();
		}
	}

	canRoleView(): boolean {
		return this.can(Permission.ROLE_VIEW);
	}

	roleView(): void | never {
		if (!this.canRoleView()) {
			this.throw();
		}
	}

	canSessionCancel(): boolean {
		return this.can(Permission.SESSION_CANCEL);
	}

	sessionCancel(): void | never {
		if (!this.canSessionCancel()) {
			this.throw();
		}
	}

	canSessionEnd(): boolean {
		return this.can(Permission.SESSION_END);
	}

	sessionEnd(): void | never {
		if (!this.canSessionEnd()) {
			this.throw();
		}
	}

	canSessionPermission(): boolean {
		return this.can(Permission.SESSION_PERMISSION);
	}

	sessionPermission(): void | never {
		if (!this.canSessionPermission()) {
			this.throw();
		}
	}

	canSessionRetrieveSecret(): boolean {
		return this.can(Permission.SESSION_RETRIEVE_SECRET);
	}

	sessionRetrieveSecret(): void | never {
		if (!this.canSessionRetrieveSecret()) {
			this.throw();
		}
	}

	canSessionStart(): boolean {
		return this.can(Permission.SESSION_START);
	}

	sessionStart(): void | never {
		if (!this.canSessionStart()) {
			this.throw();
		}
	}

	canSessionTerminate(): boolean {
		if (this.can(Permission.SESSION_TERMINATE_ANY)) {
			return true;
		}
		return this.can(Permission.SESSION_TERMINATE);
	}

	sessionTerminate(): void | never {
		if (!this.canSessionTerminate()) {
			this.throw();
		}
	}

	canSessionTerminateAny(): boolean {
		return this.can(Permission.SESSION_TERMINATE_ANY);
	}

	sessionTerminateAny(): void | never {
		if (!this.canSessionTerminateAny()) {
			this.throw();
		}
	}

	canSessionView(): boolean {
		return this.can(Permission.SESSION_VIEW);
	}

	sessionView(): void | never {
		if (!this.canSessionView()) {
			this.throw();
		}
	}

	canUserChangePassword(): boolean {
		return this.can(Permission.USER_CHANGE_PASSWORD);
	}

	userChangePassword(): void | never {
		if (!this.canUserChangePassword()) {
			this.throw();
		}
	}

	canUserCreate(): boolean {
		return this.can(Permission.USER_CREATE);
	}

	userCreate(): void | never {
		if (!this.canUserCreate()) {
			this.throw();
		}
	}

	canUserDeleteAny(): boolean {
		return this.can(Permission.USER_DELETE_ANY);
	}

	userDeleteAny(): void | never {
		if (!this.canUserDeleteAny()) {
			this.throw();
		}
	}

	canUserEnrollTwoFactorAuthentication(): boolean {
		if (this.can(Permission.USER_ENROLL_TWO_FACTOR_AUTHENTICATION_ANY)) {
			return true;
		}
		return this.can(Permission.USER_ENROLL_TWO_FACTOR_AUTHENTICATION);
	}

	userEnrollTwoFactorAuthentication(): void | never {
		if (!this.canUserEnrollTwoFactorAuthentication()) {
			this.throw();
		}
	}

	canUserEnrollTwoFactorAuthenticationAny(): boolean {
		return this.can(Permission.USER_ENROLL_TWO_FACTOR_AUTHENTICATION_ANY);
	}

	userEnrollTwoFactorAuthenticationAny(): void | never {
		if (!this.canUserEnrollTwoFactorAuthenticationAny()) {
			this.throw();
		}
	}

	canUserResetPasswordAny(): boolean {
		return this.can(Permission.USER_RESET_PASSWORD_ANY);
	}

	userResetPasswordAny(): void | never {
		if (!this.canUserResetPasswordAny()) {
			this.throw();
		}
	}

	canUserUpdate(): boolean {
		if (this.can(Permission.USER_UPDATE_ANY)) {
			return true;
		}
		return this.can(Permission.USER_UPDATE);
	}

	userUpdate(): void | never {
		if (!this.canUserUpdate()) {
			this.throw();
		}
	}

	canUserUpdateAny(): boolean {
		return this.can(Permission.USER_UPDATE_ANY);
	}

	userUpdateAny(): void | never {
		if (!this.canUserUpdateAny()) {
			this.throw();
		}
	}

	canUserView(): boolean {
		if (this.can(Permission.USER_VIEW_ANY)) {
			return true;
		}
		return this.can(Permission.USER_VIEW);
	}

	userView(): void | never {
		if (!this.canUserView()) {
			this.throw();
		}
	}

	canUserViewAny(): boolean {
		return this.can(Permission.USER_VIEW_ANY);
	}

	userViewAny(): void | never {
		if (!this.canUserViewAny()) {
			this.throw();
		}
	}

	canUserGroupAddUser(): boolean {
		return this.can(Permission.USER_GROUP_ADD_USER);
	}

	userGroupAddUser(): void | never {
		if (!this.canUserGroupAddUser()) {
			this.throw();
		}
	}

	canUserGroupCreate(): boolean {
		return this.can(Permission.USER_GROUP_CREATE);
	}

	userGroupCreate(): void | never {
		if (!this.canUserGroupCreate()) {
			this.throw();
		}
	}

	canUserGroupDelete(): boolean {
		return this.can(Permission.USER_GROUP_DELETE);
	}

	userGroupDelete(): void | never {
		if (!this.canUserGroupDelete()) {
			this.throw();
		}
	}

	canUserGroupRemoveUser(): boolean {
		return this.can(Permission.USER_GROUP_REMOVE_USER);
	}

	userGroupRemoveUser(): void | never {
		if (!this.canUserGroupRemoveUser()) {
			this.throw();
		}
	}

	canUserGroupUpdate(): boolean {
		return this.can(Permission.USER_GROUP_UPDATE);
	}

	userGroupUpdate(): void | never {
		if (!this.canUserGroupUpdate()) {
			this.throw();
		}
	}

	canUserGroupView(): boolean {
		return this.can(Permission.USER_GROUP_VIEW);
	}

	userGroupView(): void | never {
		if (!this.canUserGroupView()) {
			this.throw();
		}
	}

	// ------------------------------------------------------------
	// AUTO GENERATED SECTION END
	// ------------------------------------------------------------
}
