// Generated by Grafana k6 Studio (1.8.0) on 2025-10-14T09:59:32.689Z

import { group, sleep, check } from 'k6';
import http from 'k6/http';
import execution from 'k6/execution';

export const options = {
	stages: [
		{ target: 20, duration: '1m' },
		{ target: 20, duration: '3m30s' },
		{ target: 0, duration: '1m' }
	]
};

export default function () {
	let params;
	let resp;
	let match;
	let regex;
	let url;
	const correlation_vars = {};

	group('Default group', function () {
		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				'sec-ch-ua-platform': `"macOS"`,
				'Upgrade-Insecure-Requests': `1`,
				Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
				'Sec-Fetch-Site': `none`,
				'Sec-Fetch-Mode': `navigate`,
				'Sec-Fetch-User': `?1`,
				'Sec-Fetch-Dest': `document`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				accept: `application/json`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'content-type': `application/x-www-form-urlencoded`,
				'sec-ch-ua-mobile': `?0`,
				'x-sveltekit-action': `true`,
				Origin: `https://argus.pam`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/auth/login`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/auth/login`;
		resp = http.request(
			'POST',
			url,
			JSON.parse(`{"email":"heanluen@gmail.com","password":"password","__superform_id":"1p3ituu"}`),
			params
		);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				accept: `application/json`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'content-type': `application/x-www-form-urlencoded`,
				'sec-ch-ua-mobile': `?0`,
				'x-sveltekit-action': `true`,
				Origin: `https://argus.pam`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/auth/2fa`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/auth/2fa`;
		resp = http.request(
			'POST',
			url,
			JSON.parse(
				`{"temp_key":"jKZkdv1jFn75iqz4X9PQkU3tnXrgIF5Q","code":"585246","__superform_id":"87tvg0"}`
			),
			params
		);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'Content-Type': `text/plain;charset=UTF-8`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				Origin: `https://argus.pam`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/dashboard`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/org/switch`;
		resp = http.request('POST', url, `{"orgId":2}`, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'Content-Type': `text/plain;charset=UTF-8`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				Origin: `https://argus.pam`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/dashboard`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/org/switch`;
		resp = http.request('POST', url, `{"orgId":3}`, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'Content-Type': `text/plain;charset=UTF-8`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				Origin: `https://argus.pam`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/dashboard`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/org/switch`;
		resp = http.request('POST', url, `{"orgId":1}`, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				accept: `application/json`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'content-type': `application/x-www-form-urlencoded`,
				'sec-ch-ua-mobile': `?0`,
				'x-sveltekit-action': `true`,
				Origin: `https://argus.pam`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/requests/assets`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/requests/assets`;
		resp = http.request(
			'POST',
			url,
			JSON.parse(
				`{"asset_id":"27","org_id":"1","start_datetime":"Tue Oct 21 2025 17:45:00 GMT+0800 (Singapore Standard Time)","end_datetime":"Thu Oct 30 2025 17:45:00 GMT+0800 (Singapore Standard Time)","reason":"qwe","intended_query":"qwe","scope":"ReadOnly","__superform_id":"10e8w1p"}`
			),
			params
		);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/requests`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/requests?page=1&sort=-created_at&include=asset%2Crequester%2Capprover%2Crejecter`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/assets`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/assets?page=1`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/organizations`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/orgs?page=1`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/organizations/user-groups`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/user-groups?page=1&count=users`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/users`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/users?page=1`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/users/roles`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/roles?page=1`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/users/permissions`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/permissions?page=1`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'sec-ch-ua-platform': `"macOS"`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				Accept: `*/*`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `cors`,
				'Sec-Fetch-Dest': `empty`,
				Referer: `https://argus.pam/users/permissions?page=1`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/api/search/permissions?page=2`;
		resp = http.request('GET', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });

		params = {
			headers: {
				Connection: `keep-alive`,
				'Cache-Control': `max-age=0`,
				'sec-ch-ua': `"Google Chrome";v="141", "Not?A_Brand";v="8", "Chromium";v="141"`,
				'sec-ch-ua-mobile': `?0`,
				'sec-ch-ua-platform': `"macOS"`,
				Origin: `https://argus.pam`,
				'Content-Type': `application/x-www-form-urlencoded`,
				'Upgrade-Insecure-Requests': `1`,
				Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
				'Sec-Fetch-Site': `same-origin`,
				'Sec-Fetch-Mode': `navigate`,
				'Sec-Fetch-User': `?1`,
				'Sec-Fetch-Dest': `document`,
				Referer: `https://argus.pam/settings/security`,
				'Accept-Encoding': `gzip, deflate, br, zstd`,
				'Accept-Language': `en-GB,en-US;q=0.9,en;q=0.8`
			},
			cookies: {}
		};

		url = http.url`https://argus.pam/auth/logout`;
		resp = http.request('POST', url, null, params);

		check(resp, { 'status equals 200': (r) => r.status === 200 });
	});
	sleep(Math.random() * (2 - 1) + 1);
}
